apiVersion: apps/v1 
kind: Deployment
metadata:
  name: api-deployment
  labels: 
    service: api-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: korobokvk/reporty-client-service-api:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env: 
        - name: AUTH_SERVICE
          value: "auth-service:3000"