apiVersion: apps/v1 
kind: Deployment
metadata:
  name: auth-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: korobokvk/reporty-auth-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3020