apiVersion: apps/v1 
kind: Deployment
metadata:
  name: db-deployment
  labels:
    service: db-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: korobokvk/reporty-db-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 