apiVersion: apps/v1 
kind: Deployment
metadata:
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: db-service
  template:
    metadata:
      labels:
        app: db-service
    spec:
      containers:
      - name: db-service
        image: korobokvk/reporty-db-service:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3010 