version: "3.7"
services:
  auth:
    container_name: "reporty-auth-service"
    image: "reporty-auth-service"
    build: 
      context: ./main/reporty-auth-service
      dockerfile: Dockerfile
    volumes: 
      - ./main/reporty-auth-service:/usr/src/app:cached
      - ./main/reporty-auth-service/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - "3001:3000"
  data:
    container_name: data-generator
    image: "data-generator"
    build: 
      context: ./main/data-generator
      dockerfile: Dockerfile
    volumes: 
      - ./main/data-generator:/usr/src/app:cached
      - ./main/data-generator/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - "3002:3000"
  client:
    container_name: reporty-client-server
    image: "reporty-client-server"
    build: 
      context: ./main/reporty-client-server
      dockerfile: Dockerfile
    volumes: 
      - ./main/reporty-client-server:/usr/src/app:cached
      - ./main/reporty-client-server/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - "3003:3000"
  # For now is it will be a static
  # front-end:
  #   image: "client-server"
  #   ports: 
  #     - "3003:3000"