version: '3'

services:


  api:
    container_name: "reporty-client-service-api"
    environment: 
      AUTH_SERVICE_URL: host.docker.internal:3020
    build:
      context: ./main/reporty-client-service-api
      dockerfile: Dockerfile.dev
    volumes: 
      - ./main/reporty-client-service-api:/usr/src/app:cached
      - ./main/reporty-client-service-api/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - 3030:3000
    restart: "on-failure"

  service:
    container_name: "reporty-client-service"
    build:
      context: ./main/reporty-client-service
      dockerfile: Dockerfile.dev
    volumes: 
      - ./main/reporty-client-service:/usr/src/app:cached
      - ./main/reporty-client-service/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - 3040:3000
    restart: "on-failure"

  auth:
    container_name: "reporty-auth-service"
    build: 
      context: ./main/reporty-auth-service
      dockerfile: Dockerfile.dev
    volumes: 
      - ./main/reporty-auth-service:/usr/src/app:cached
      - ./main/reporty-auth-service/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - 3020:3000
    restart: "on-failure"

  provider:
    container_name: reporty-db-provider
    build: 
      context: ./main/reporty-db-provider
      dockerfile: Dockerfile
    volumes: 
      - ./main/reporty-db-provider:/usr/src/app:cached
      - ./main/reporty-db-provider/node_modules:/usr/src/app/node_modules:cached
    restart: on-failure
    ports: 
      - 3010:3000

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment: 
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    networks:
      - postgres
    ports:
      - 5432:5432
# #It's dummy data for app 
  data:
    container_name: data-generator
    build: 
      context: ./main/data-generator
      dockerfile: Dockerfile
    volumes: 
      - ./main/data-generator:/usr/src/app:cached
      - ./main/data-generator/node_modules:/usr/src/app/node_modules:cached
    ports: 
      - 3002:3000
    restart: "on-failure"

networks:
  postgres:
    driver: bridge
